# Generated by Django 5.1 on 2024-09-12 12:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_obj',
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=datetime.datetime(2024, 9, 12, 12, 30, 37, 741914, tzinfo=datetime.timezone.utc), max_length=221),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 9, 12, 12, 30, 48, 32682, tzinfo=datetime.timezone.utc), upload_to='author_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
