# Generated by Django 5.1 on 2024-09-12 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_remove_comment_comment_obj_article_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 12, 12, 35, 58, 872044, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
